# Generated by Django 3.2.8 on 2022-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_request_query_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='post_body',
            field=models.JSONField(default=dict, verbose_name='post_body'),
        ),
        migrations.AlterField(
            model_name='request',
            name='query_params',
            field=models.JSONField(default=dict, verbose_name='query_params'),
        ),
    ]
